"""Canonical public API for the :mod:`innovate` package."""

from __future__ import annotations

from importlib import import_module
from importlib.metadata import PackageNotFoundError, version
from typing import Any

from .base import DiffusionModel
from .capabilities import (
    BackendCapability,
    FitterCapability,
    ModelCapability,
    get_backend_capability,
    get_backend_registry,
    get_fitter_capability,
    get_fitter_registry,
    get_model_capability,
    get_model_registry,
)
from .plugins import ExtensionManifest, get_registered_extensions, register_extension
from .stability import StabilityTier, describe_stability_tier, normalize_stability_tier

try:
    __version__ = version("innovate")
except PackageNotFoundError:  # pragma: no cover - local source tree without install metadata
    __version__ = "0.0.0"

_LAZY_EXPORTS: dict[str, tuple[str, str | None]] = {
    "backend": ("innovate.backend", None),
    "advanced_runtime": ("innovate.advanced_runtime", None),
    "backends": ("innovate.backends", None),
    "benchmarks": ("innovate.benchmarks", None),
    "arrow_interchange": ("innovate.arrow_interchange", None),
    "compete": ("innovate.compete", None),
    "dataframe_engines": ("innovate.dataframe_engines", None),
    "diffuse": ("innovate.diffuse", None),
    "ecosystem": ("innovate.ecosystem", None),
    "fitters": ("innovate.fitters", None),
    "kernel": ("innovate.kernel", None),
    "models": ("innovate.models", None),
    "probabilistic": ("innovate.probabilistic", None),
    "remote_execution": ("innovate.remote_execution", None),
    "substitute": ("innovate.substitute", None),
    "BassModel": ("innovate.diffuse", "BassModel"),
    "GompertzModel": ("innovate.diffuse", "GompertzModel"),
    "LogisticModel": ("innovate.diffuse", "LogisticModel"),
    "CompositeDiffusionModel": ("innovate.substitute", "CompositeDiffusionModel"),
    "FisherPryModel": ("innovate.substitute", "FisherPryModel"),
    "NortonBassModel": ("innovate.substitute", "NortonBassModel"),
    "LotkaVolterraModel": ("innovate.compete", "LotkaVolterraModel"),
    "MultiProductDiffusionModel": ("innovate.compete", "MultiProductDiffusionModel"),
    "ComplementaryGoodsModel": ("innovate.ecosystem", "ComplementaryGoodsModel"),
    "AdvancedDiffusionModel": ("innovate.models", "AdvancedDiffusionModel"),
    "AdvancedModelSummary": ("innovate.models", "AdvancedModelSummary"),
    "BenchmarkCase": ("innovate.benchmarks", "BenchmarkCase"),
    "BenchmarkAutomationReport": ("innovate.benchmarks", "BenchmarkAutomationReport"),
    "BenchmarkJob": ("innovate.benchmarks", "BenchmarkJob"),
    "BenchmarkFamily": ("innovate.benchmarks", "BenchmarkFamily"),
    "BenchmarkRun": ("innovate.benchmarks", "BenchmarkRun"),
    "BenchmarkRunner": ("innovate.benchmarks", "BenchmarkRunner"),
    "BenchmarkSuiteResult": ("innovate.benchmarks", "BenchmarkSuiteResult"),
    "BenchmarkValidationIssue": ("innovate.benchmarks", "BenchmarkValidationIssue"),
    "AdvancedBackendSelection": ("innovate.advanced_runtime", "AdvancedBackendSelection"),
    "AdvancedCapability": ("innovate.advanced_runtime", "AdvancedCapability"),
    "AdvancedResult": ("innovate.advanced_runtime", "AdvancedResult"),
    "AdvancedRuntimePolicy": ("innovate.advanced_runtime", "AdvancedRuntimePolicy"),
    "DataFrameEngineBenchmarkFixture": (
        "innovate.dataframe_engines",
        "DataFrameEngineBenchmarkFixture",
    ),
    "ModelCard": ("innovate.benchmarks", "ModelCard"),
    "InProcessRemoteExecutor": ("innovate.remote_execution", "InProcessRemoteExecutor"),
    "RemoteExecutionContext": ("innovate.remote_execution", "RemoteExecutionContext"),
    "RemoteExecutionPolicy": ("innovate.remote_execution", "RemoteExecutionPolicy"),
    "RemoteExecutionRequest": ("innovate.remote_execution", "RemoteExecutionRequest"),
    "RemoteExecutionResponse": ("innovate.remote_execution", "RemoteExecutionResponse"),
    "HierarchicalModel": ("innovate.models", "HierarchicalModel"),
    "NetworkDiffusionInputs": ("innovate.models", "NetworkDiffusionInputs"),
    "NetworkDiffusionModel": ("innovate.models", "NetworkDiffusionModel"),
    "LatentProcessDiffusionModel": ("innovate.models", "LatentProcessDiffusionModel"),
    "MixtureModel": ("innovate.models", "MixtureModel"),
    "PolicyHazardDiffusionModel": ("innovate.models", "PolicyHazardDiffusionModel"),
    "PolicyTimingInputs": ("innovate.models", "PolicyTimingInputs"),
    "RegimeSwitchingDiffusionModel": ("innovate.models", "RegimeSwitchingDiffusionModel"),
    "BatchedFitter": ("innovate.fitters", "BatchedFitter"),
    "BayesianFitter": ("innovate.fitters", "BayesianFitter"),
    "BlackJaxFitter": ("innovate.fitters", "BlackJaxFitter"),
    "BootstrapFitter": ("innovate.fitters", "BootstrapFitter"),
    "CurveFitter": ("innovate.fitters", "CurveFitter"),
    "JaxFitter": ("innovate.fitters", "JaxFitter"),
    "MoMFitter": ("innovate.fitters", "MoMFitter"),
    "ScipyFitter": ("innovate.fitters", "ScipyFitter"),
    "get_backend_capability": ("innovate.capabilities", "get_backend_capability"),
    "get_backend_registry": ("innovate.capabilities", "get_backend_registry"),
    "get_benchmark_case": ("innovate.benchmarks", "get_benchmark_case"),
    "describe_benchmark_automation": ("innovate.benchmarks", "describe_benchmark_automation"),
    "describe_dataframe_engine_experiments": (
        "innovate.dataframe_engines",
        "describe_dataframe_engine_experiments",
    ),
    "describe_remote_execution_contract": ("innovate.remote_execution", "describe_remote_execution_contract"),
    "list_benchmark_jobs": ("innovate.benchmarks", "list_benchmark_jobs"),
    "get_fitter_capability": ("innovate.capabilities", "get_fitter_capability"),
    "get_fitter_registry": ("innovate.capabilities", "get_fitter_registry"),
    "get_model_card": ("innovate.benchmarks", "get_model_card"),
    "list_benchmark_cases": ("innovate.benchmarks", "list_benchmark_cases"),
    "list_model_cards": ("innovate.benchmarks", "list_model_cards"),
    "refresh_model_card_summaries": ("innovate.benchmarks", "refresh_model_card_summaries"),
    "run_stable_benchmark_suite": ("innovate.benchmarks", "run_stable_benchmark_suite"),
    "validate_benchmark_corpus": ("innovate.benchmarks", "validate_benchmark_corpus"),
    "calibrate_prediction_intervals": ("innovate.advanced_runtime", "calibrate_prediction_intervals"),
    "compare_policy_scenarios": ("innovate.advanced_runtime", "compare_policy_scenarios"),
    "compose_regime_ensemble": ("innovate.advanced_runtime", "compose_regime_ensemble"),
    "detect_advanced_backends": ("innovate.advanced_runtime", "detect_advanced_backends"),
    "get_advanced_capability": ("innovate.advanced_runtime", "get_advanced_capability"),
    "list_advanced_capabilities": ("innovate.advanced_runtime", "list_advanced_capabilities"),
    "select_advanced_backend": ("innovate.advanced_runtime", "select_advanced_backend"),
    "update_streaming_forecast": ("innovate.advanced_runtime", "update_streaming_forecast"),
}

__all__ = [
    "AdvancedBackendSelection",
    "AdvancedCapability",
    "AdvancedDiffusionModel",
    "AdvancedModelSummary",
    "AdvancedResult",
    "AdvancedRuntimePolicy",
    "BackendCapability",
    "BassModel",
    "BatchedFitter",
    "BayesianFitter",
    "BenchmarkAutomationReport",
    "BenchmarkCase",
    "BenchmarkFamily",
    "BenchmarkJob",
    "BenchmarkRun",
    "BenchmarkRunner",
    "BenchmarkSuiteResult",
    "BenchmarkValidationIssue",
    "BlackJaxFitter",
    "BootstrapFitter",
    "ComplementaryGoodsModel",
    "CompositeDiffusionModel",
    "CurveFitter",
    "DataFrameEngineBenchmarkFixture",
    "DiffusionModel",
    "ExtensionManifest",
    "FisherPryModel",
    "FitterCapability",
    "GompertzModel",
    "HierarchicalModel",
    "InProcessRemoteExecutor",
    "JaxFitter",
    "LatentProcessDiffusionModel",
    "LogisticModel",
    "LotkaVolterraModel",
    "MixtureModel",
    "MoMFitter",
    "ModelCapability",
    "ModelCard",
    "MultiProductDiffusionModel",
    "NetworkDiffusionInputs",
    "NetworkDiffusionModel",
    "NortonBassModel",
    "PolicyHazardDiffusionModel",
    "PolicyTimingInputs",
    "RegimeSwitchingDiffusionModel",
    "RemoteExecutionContext",
    "RemoteExecutionPolicy",
    "RemoteExecutionRequest",
    "RemoteExecutionResponse",
    "ScipyFitter",
    "StabilityTier",
    "__version__",
    "advanced_runtime",
    "arrow_interchange",
    "backend",
    "backends",
    "benchmarks",
    "calibrate_prediction_intervals",
    "compare_policy_scenarios",
    "compete",
    "compose_regime_ensemble",
    "dataframe_engines",
    "describe_benchmark_automation",
    "describe_dataframe_engine_experiments",
    "describe_stability_tier",
    "detect_advanced_backends",
    "diffuse",
    "ecosystem",
    "fitters",
    "get_advanced_capability",
    "get_backend_capability",
    "get_backend_registry",
    "get_benchmark_case",
    "get_fitter_capability",
    "get_fitter_registry",
    "get_model_capability",
    "get_model_card",
    "get_model_registry",
    "get_registered_extensions",
    "kernel",
    "list_advanced_capabilities",
    "list_benchmark_cases",
    "list_benchmark_jobs",
    "list_model_cards",
    "models",
    "normalize_stability_tier",
    "probabilistic",
    "refresh_model_card_summaries",
    "register_extension",
    "remote_execution",
    "run_stable_benchmark_suite",
    "select_advanced_backend",
    "substitute",
    "update_streaming_forecast",
    "validate_benchmark_corpus",
]


def __getattr__(name: str) -> Any:
    """Lazily resolve the documented public API surface."""
    if name not in _LAZY_EXPORTS:
        raise AttributeError(f"module {__name__!r} has no attribute {name!r}")

    module_name, attr_name = _LAZY_EXPORTS[name]
    module = import_module(module_name)
    value = module if attr_name is None else getattr(module, attr_name)
    globals()[name] = value
    return value


def __dir__() -> list[str]:
    return sorted(set(globals()) | set(__all__) | set(_LAZY_EXPORTS))
