# Configuration for Release Drafter
# https://github.com/release-drafter/release-drafter

name-template: 'v$NEXT_PATCH_VERSION'
tag-template: 'v$NEXT_PATCH_VERSION'
categories:
  - title: '✨ Features'
    labels:
      - 'feature'
      - 'enhancement'
  - title: '🐛 Bug Fixes'
    labels:
      - 'fix'
      - 'bug'
  - title: '📚 Documentation'
    labels:
      - 'docs'
      - 'documentation'
  - title: '🔨 Maintenance'
    labels:
      - 'maintenance'
      - 'chore'
      - 'ci'
change-template: '- $TITLE @$AUTHOR (#$NUMBER)'
template: |
  ## Changes

  $CHANGES
