repos:
  - repo: https://github.com/psf/black
    rev: 23.1.0
    hooks:
      - id: black
        language_version: python3

  - repo: https://github.com/pycqa/isort
    rev: 5.12.0
    hooks:
      - id: isort
        name: isort (python)

  - repo: https://github.com/pycqa/flake8
    rev: 6.0.0
    hooks:
      - id: flake8

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.1.1
    hooks:
      - id: mypy
        additional_dependencies: [types-setuptools]

  - repo: https://github.com/codespell-project/codespell
    rev: v2.2.2
    hooks:
      - id: codespell
        args: [--write-changes]

  - repo: https://github.com/kynan/nbstripout
    rev: 0.6.1
    hooks:
      - id: nbstripout
        files: \.ipynb$
        args: [--drop-empty-cells]

  - repo: https://github.com/pycqa/vulture
    rev: v2.11
    hooks:
      - id: vulture
        args: [--min-confidence=60]

  - repo: https://github.com/hakancelik96/unimport
    rev: v0.17.0
    hooks:
      - id: unimport
        args: [--check]