"""Explainability, sensitivity analysis, and decision-report artifacts."""

from innovate.reports.claims import (
    CLAIM_TYPES,
    FORBIDDEN_RECOMMENDATION_PHRASES,
    REPORT_SCHEMA_VERSION,
    SAFE_INTERPRETATION_BY_CLAIM,
    ClaimRecord,
    ClaimType,
    assert_safe_public_wording,
    claim_safety_summary,
    classify_claim,
)
from innovate.reports.explainability import (
    adoption_driver_summary,
    combine_explainability,
    competition_effect_summary,
    policy_component_summary,
    substitution_threshold_summary,
)
from innovate.reports.export import (
    example_competition_report,
    example_policy_report,
    example_substitution_report,
    export_examples,
    export_report_json,
    export_report_markdown,
    report_from_mapping,
)
from innovate.reports.schemas import DecisionReport, WorkflowFamily, build_decision_report
from innovate.reports.sensitivity import (
    AssumptionSensitivityInput,
    ParameterSensitivityInput,
    ThresholdSensitivityInput,
    TimingSensitivityInput,
    assumption_sensitivity_summary,
    combine_sensitivity_summaries,
    intervention_timing_summary,
    parameter_perturbation_summary,
    threshold_sensitivity_summary,
)

__all__ = [
    "CLAIM_TYPES",
    "FORBIDDEN_RECOMMENDATION_PHRASES",
    "REPORT_SCHEMA_VERSION",
    "SAFE_INTERPRETATION_BY_CLAIM",
    "AssumptionSensitivityInput",
    "ClaimRecord",
    "ClaimType",
    "DecisionReport",
    "ParameterSensitivityInput",
    "ThresholdSensitivityInput",
    "TimingSensitivityInput",
    "WorkflowFamily",
    "adoption_driver_summary",
    "assert_safe_public_wording",
    "assumption_sensitivity_summary",
    "build_decision_report",
    "claim_safety_summary",
    "classify_claim",
    "combine_explainability",
    "combine_sensitivity_summaries",
    "competition_effect_summary",
    "example_competition_report",
    "example_policy_report",
    "example_substitution_report",
    "export_examples",
    "export_report_json",
    "export_report_markdown",
    "intervention_timing_summary",
    "parameter_perturbation_summary",
    "policy_component_summary",
    "report_from_mapping",
    "substitution_threshold_summary",
    "threshold_sensitivity_summary",
]
