package:
  name: innovate
  version: "0.2.1"

source:
  path: ..

build:
  noarch: python
  script: bash build.sh

requirements:
  host:
    - python >=3.8
    - pip
    - setuptools
    - wheel
  run:
    - python >=3.8
    - numpy
    - scipy
    - pandas
    - statsmodels
    - pyarrow
    - mesa
    - networkx
    - pip
  run_constrained:
    - jitcdde

about:
  home: https://github.com/edithatogo/innovate
  license: Apache-2.0
  license_file: LICENSE
  summary: "A Python library for simplifying innovation/policy diffusion modelling."
