# This workflow is based on the example from:
# https://github.com/conda-incubator/setup-miniconda

name: Publish Conda Package

on:
  release:
    types: [published]

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up conda environment
        uses: conda-incubator/setup-miniconda@v3
        with:
          auto-update-conda: true
          python-version: "3.10"
          channels: conda-forge,defaults
          channel-priority: strict

      - name: Build conda package
        shell: bash -l {0}
        run: conda build .

      - name: Publish to Anaconda
        shell: bash -l {0}
        env:
          ANACONDA_API_TOKEN: ${{ secrets.ANACONDA_API_TOKEN }}
        run: |
          conda install anaconda-client
          anaconda -t "$ANACONDA_API_TOKEN" upload --user edithatogo --label main $(conda build . --output)
