name: Release Please

on:
  push:
    branches: [main]

permissions:
  contents: write
  pull-requests: write

jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - uses: googleapis/release-please-action@512809dcf9829afec14e6677ccddce3d9ba6cdfe # v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          release-type: python
          skip-github-pull-request: true
