name: TagBot

on:
  issue_comment:
    types: [created]
  workflow_dispatch:

permissions:
  contents: write
  issues: read
  pull-requests: read

jobs:
  tagbot:
    runs-on: ubuntu-latest
    steps:
      - uses: JuliaRegistries/TagBot@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
