name: Publish to TestPyPI

permissions:
  contents: read

on:
  release:
    types: [published]

jobs:
  pypi-publish:
    name: Upload release to TestPyPI
    runs-on: ubuntu-latest
    environment:
      name: testpypi
      url: https://test.pypi.org/p/innovate
    permissions:
      id-token: write # IMPORTANT: this permission is mandatory for trusted publishing
    steps:
      - name: Checkout code
        uses: actions/checkout@6026fb2ad3aa556d78b517cf65c8c1f832075860
        with:
          persist-credentials: false

      - name: Install uv
        uses: astral-sh/setup-uv@11f9893b081a58869d3b5fccaea48c9e9e46f990

      - name: Set up Python
        run: uv python install 3.14

      - name: Install dependencies
        run: uv sync

      - name: Build package
        run: uv build

      - name: Validate package metadata
        run: uv run twine check dist/*

      - name: Publish package to TestPyPI
        uses: pypa/gh-action-pypi-publish@ba38be9e461d3875417946c167d0b5f3d385a247
        with:
          user: __token__
          password: ${{ secrets.TEST_PYPI_API_TOKEN }}
          repository-url: https://test.pypi.org/legacy/
