name: Publish to TestPyPI

on:
  release:
    types: [published]

jobs:
  pypi-publish:
    name: Upload release to TestPyPI
    runs-on: ubuntu-latest
    environment:
      name: testpypi
      url: https://test.pypi.org/p/innovate
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Checkout code
        uses: actions/checkout@6026fb2ad3aa556d78b517cf65c8c1f832075860 # v5
        with:
          persist-credentials: false

      - name: Install uv
        uses: astral-sh/setup-uv@08807647e7069bb48b6ef5acd8ec9567f424441b # v8.1.0
        with:
          enable-cache: false

      - name: Set up Python
        run: uv python install 3.14

      - name: Install dependencies
        run: uv sync

      - name: Build package
        run: uv build

      - name: Validate package metadata
        run: uv run twine check dist/*

      - name: Publish package to TestPyPI
        uses: pypa/gh-action-pypi-publish@716c507c5a083a216fcb67ba395f190a6ea5b106 # release/v1
        with:
          repository-url: https://test.pypi.org/legacy/
